
# 站点设置
title: weiwei.blog
description: haojixing buru lanbitou
url: "https://weiweiok.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
# permalink: /:categories/:title.html

# 分类设置
ww_categories: [
["php",  "PHP笔记"], 
["js",   "javascript"],
["git",  "github"]
]




# 编码设置
encoding: UTF-8

# Markdown 渲染引擎设置
markdown: kramdown
kramdown:
input: GFM
syntax_highlighter: rouge

# 摘要分隔符设置
excerpt_separator: "\n\n\n\n"

# 分页设置
gems: [jekyll-paginate]
paginate: 5