
# Site settings
title: weiwei.blog
brief-intro: haojixing buru lanbitou
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://weiweiok.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/