
# 站点设置
title: Weiwei.Blog
description: 魏伟的博客
url: "http://weiwei.blog"
permalink: /:categories/:title.html

# 分类设置
ww_categories: [
["php",  "PHP笔记"], 
["js",   "JavaScript"],
["git",  "github"]
]




# 编码设置
encoding: UTF-8

# Markdown 渲染引擎设置
markdown: kramdown
kramdown:
syntax_highlighter: rouge

# 摘要分隔符设置
excerpt_separator: "\n\n\n\n"

# 分页设置
gems: [jekyll-paginate]
paginate: 5